package br.com.model;

// Generated 26/10/2012 15:13:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.Range;

/**
 * Diario generated by hbm2java
 */
@Entity
@Table(name = "diario", catalog = "geng")
public class Diario implements java.io.Serializable {

	private Integer codigo;
	private Servico servico;
	private Trabalhador trabalhador;
	private Unidade unidade;
	private Date data;
	private String lote;
	private Long producaoacordada;
	private Long producaoexecutada;
	private Date horaextra;
	private double salario;
	private Double vhextra;
	private Double vinsalubridade;

	public Diario() {
	}

	public Diario(Servico servico, Trabalhador trabalhador, Unidade unidade,
			Date data, String lote, Long producaoacordada, double salario) {
		this.servico = servico;
		this.trabalhador = trabalhador;
		this.unidade = unidade;
		this.data = data;
		this.lote = lote;
		this.producaoacordada = producaoacordada;
		this.salario = salario;
	}

	public Diario(Servico servico, Trabalhador trabalhador, Unidade unidade,
			Date data, String lote, Long producaoacordada,
			Long producaoexecutada, Date horaextra, double salario,
			Double vhextra, Double vinsalubridade) {
		this.servico = servico;
		this.trabalhador = trabalhador;
		this.unidade = unidade;
		this.data = data;
		this.lote = lote;
		this.producaoacordada = producaoacordada;
		this.producaoexecutada = producaoexecutada;
		this.horaextra = horaextra;
		this.salario = salario;
		this.vhextra = vhextra;
		this.vinsalubridade = vinsalubridade;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@NotNull(message="Campo Serviço: Obrigatório")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "servico", nullable = false)
	public Servico getServico() {
		return this.servico;
	}

	public void setServico(Servico servico) {
		this.servico = servico;
	}

	@NotNull(message="Campo Trabalhador: Obrigatório")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trabalhador", nullable = false)
	public Trabalhador getTrabalhador() {
		return this.trabalhador;
	}

	public void setTrabalhador(Trabalhador trabalhador) {
		this.trabalhador = trabalhador;
	}

	@NotNull(message="Campo Unidade: Obrigatório")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidade", nullable = false)
	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

	@NotNull(message="Campo Data: Obrigatório")
	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@NotEmpty(message="Campo Lote: Obrigatório")
	@Column(name = "lote", nullable = false, length = 10)
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	@NotNull(message="Campo Produção Acordada: Obrigatório")
	@Range(min=1, max=999999999, message="Campo Produção Acordada: Tamanho mínimo de 1 dígito")
	@Column(name = "producaoacordada", nullable = false)
	public Long getProducaoacordada() {
		return this.producaoacordada;
	}

	public void setProducaoacordada(Long producaoacordada) {
		this.producaoacordada = producaoacordada;
	}

	@Column(name = "producaoexecutada")
	public Long getProducaoexecutada() {
		return this.producaoexecutada;
	}

	public void setProducaoexecutada(Long producaoexecutada) {
		this.producaoexecutada = producaoexecutada;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaextra", length = 8)
	public Date getHoraextra() {
		return this.horaextra;
	}

	public void setHoraextra(Date horaextra) {
		this.horaextra = horaextra;
	}

	@Column(name = "salario", nullable = false, precision = 5)
	public double getSalario() {
		return this.salario;
	}

	public void setSalario(double salario) {
		this.salario = salario;
	}

	@Column(name = "vhextra", precision = 5)
	public Double getVhextra() {
		return this.vhextra;
	}

	public void setVhextra(Double vhextra) {
		this.vhextra = vhextra;
	}

	@Column(name = "vinsalubridade", precision = 5)
	public Double getVinsalubridade() {
		return this.vinsalubridade;
	}

	public void setVinsalubridade(Double vinsalubridade) {
		this.vinsalubridade = vinsalubridade;
	}

}
