package br.com.model;

// Generated 26/10/2012 15:13:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recibo generated by hbm2java
 */
@Entity
@Table(name = "recibo", catalog = "geng")
public class Recibo implements java.io.Serializable {

	private Integer codigo;
	private Trabalhador trabalhador;
	private Unidade unidade;
	private Date datainicio;
	private Date datafim;
	private Integer rremunerado;
	private Double vrremunerado;
	private Integer sfamilia;
	private Double vsfamilia;
	private Double horaextra;
	private Double vhoraextra;
	private Integer insalubridade;
	private Double vinsalubridade;
	private Double ssalario;

	public Recibo() {
	}

	public Recibo(Trabalhador trabalhador, Unidade unidade, Date datainicio,
			Date datafim) {
		this.trabalhador = trabalhador;
		this.unidade = unidade;
		this.datainicio = datainicio;
		this.datafim = datafim;
	}

	public Recibo(Trabalhador trabalhador, Unidade unidade, Date datainicio,
			Date datafim, Integer rremunerado, Double vrremunerado,
			Integer sfamilia, Double vsfamilia, Double horaextra,
			Double vhoraextra, Integer insalubridade, Double vinsalubridade,
			Double ssalario) {
		this.trabalhador = trabalhador;
		this.unidade = unidade;
		this.datainicio = datainicio;
		this.datafim = datafim;
		this.rremunerado = rremunerado;
		this.vrremunerado = vrremunerado;
		this.sfamilia = sfamilia;
		this.vsfamilia = vsfamilia;
		this.horaextra = horaextra;
		this.vhoraextra = vhoraextra;
		this.insalubridade = insalubridade;
		this.vinsalubridade = vinsalubridade;
		this.ssalario = ssalario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trabalhador", nullable = false)
	public Trabalhador getTrabalhador() {
		return this.trabalhador;
	}

	public void setTrabalhador(Trabalhador trabalhador) {
		this.trabalhador = trabalhador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidade", nullable = false)
	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datainicio", nullable = false, length = 10)
	public Date getDatainicio() {
		return this.datainicio;
	}

	public void setDatainicio(Date datainicio) {
		this.datainicio = datainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datafim", nullable = false, length = 10)
	public Date getDatafim() {
		return this.datafim;
	}

	public void setDatafim(Date datafim) {
		this.datafim = datafim;
	}

	@Column(name = "rremunerado")
	public Integer getRremunerado() {
		return this.rremunerado;
	}

	public void setRremunerado(Integer rremunerado) {
		this.rremunerado = rremunerado;
	}

	@Column(name = "vrremunerado", precision = 5)
	public Double getVrremunerado() {
		return this.vrremunerado;
	}

	public void setVrremunerado(Double vrremunerado) {
		this.vrremunerado = vrremunerado;
	}

	@Column(name = "sfamilia")
	public Integer getSfamilia() {
		return this.sfamilia;
	}

	public void setSfamilia(Integer sfamilia) {
		this.sfamilia = sfamilia;
	}

	@Column(name = "vsfamilia", precision = 5)
	public Double getVsfamilia() {
		return this.vsfamilia;
	}

	public void setVsfamilia(Double vsfamilia) {
		this.vsfamilia = vsfamilia;
	}

	@Column(name = "horaextra", precision = 5)
	public Double getHoraextra() {
		return this.horaextra;
	}

	public void setHoraextra(Double horaextra) {
		this.horaextra = horaextra;
	}

	@Column(name = "vhoraextra", precision = 5)
	public Double getVhoraextra() {
		return this.vhoraextra;
	}

	public void setVhoraextra(Double vhoraextra) {
		this.vhoraextra = vhoraextra;
	}

	@Column(name = "insalubridade")
	public Integer getInsalubridade() {
		return this.insalubridade;
	}

	public void setInsalubridade(Integer insalubridade) {
		this.insalubridade = insalubridade;
	}

	@Column(name = "vinsalubridade", precision = 5)
	public Double getVinsalubridade() {
		return this.vinsalubridade;
	}

	public void setVinsalubridade(Double vinsalubridade) {
		this.vinsalubridade = vinsalubridade;
	}

	@Column(name = "ssalario", precision = 7)
	public Double getSsalario() {
		return this.ssalario;
	}

	public void setSsalario(Double ssalario) {
		this.ssalario = ssalario;
	}

}
