package br.com.model;

// Generated 26/10/2012 15:13:15 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Responsavel generated by hbm2java
 */
@Entity
@Table(name = "responsavel", catalog = "geng", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "unidade", "inscricao" }),
		@UniqueConstraint(columnNames = { "unidade", "inscricaofornecedor" }) })
public class Responsavel implements java.io.Serializable {

	private Integer codigo;
	private Unidade unidade;
	private String tipo;
	private String inscricao;
	private String rasaosocial;
	private String nome;
	private String telefone;
	private String celular;
	private String email;
	private String pais;
	private String cidade;
	private String bairro;
	private String logradouro;
	private Integer numero;
	private Integer uf;
	private String cep;
	private String complemento;
	private String tipofornecedor;
	private String inscricaofornecedor;
	private Set<Empresa> empresas = new HashSet<Empresa>(0);

	public Responsavel() {
	}

	public Responsavel(Unidade unidade, String tipo, String inscricao,
			String nome, String tipofornecedor, String inscricaofornecedor) {
		this.unidade = unidade;
		this.tipo = tipo;
		this.inscricao = inscricao;
		this.nome = nome;
		this.tipofornecedor = tipofornecedor;
		this.inscricaofornecedor = inscricaofornecedor;
	}

	public Responsavel(Unidade unidade, String tipo, String inscricao,
			String rasaosocial, String nome, String telefone, String celular,
			String email, String pais, String cidade, String bairro,
			String logradouro, Integer numero, Integer uf, String cep,
			String complemento, String tipofornecedor,
			String inscricaofornecedor, Set<Empresa> empresas) {
		this.unidade = unidade;
		this.tipo = tipo;
		this.inscricao = inscricao;
		this.rasaosocial = rasaosocial;
		this.nome = nome;
		this.telefone = telefone;
		this.celular = celular;
		this.email = email;
		this.pais = pais;
		this.cidade = cidade;
		this.bairro = bairro;
		this.logradouro = logradouro;
		this.numero = numero;
		this.uf = uf;
		this.cep = cep;
		this.complemento = complemento;
		this.tipofornecedor = tipofornecedor;
		this.inscricaofornecedor = inscricaofornecedor;
		this.empresas = empresas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@NotNull(message="Campo Unidade: Obrigatório")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidade", nullable = false)
	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

	@Column(name = "tipo", nullable = false, length = 4)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@NotEmpty(message="Campo Inscrição: Obrigatório")
	@Length(min=14, max=18, message="Campo Inscrição: Preencha de acordo com a máscara")
	@Column(name = "inscricao", nullable = false, length = 18)
	public String getInscricao() {
		return this.inscricao;
	}

	public void setInscricao(String inscricao) {
		this.inscricao = inscricao;
	}

	@NotEmpty(message="Campo Rasão Social: Obrigatório")
	@Length(min=3, max=200, message="Campo Rasão Social: Tamanho mínimo de 3 caracteres")
	@Column(name = "rasaosocial", length = 100)
	public String getRasaosocial() {
		return this.rasaosocial;
	}

	public void setRasaosocial(String rasaosocial) {
		this.rasaosocial = rasaosocial;
	}

	@Column(name = "nome", nullable = false, length = 200)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "telefone", length = 13)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "celular", length = 13)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "pais", length = 50)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "cidade", length = 100)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "bairro", length = 100)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "logradouro", length = 100)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "uf")
	public Integer getUf() {
		return this.uf;
	}

	public void setUf(Integer uf) {
		this.uf = uf;
	}

	@Column(name = "cep", length = 11)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "complemento", length = 100)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "tipofornecedor", nullable = false, length = 4)
	public String getTipofornecedor() {
		return this.tipofornecedor;
	}

	public void setTipofornecedor(String tipofornecedor) {
		this.tipofornecedor = tipofornecedor;
	}

	@NotEmpty(message="Campo Inscrição Fornecedor: Obrigatório")
	@Length(min=14, max=18, message="Campo Inscrição Fornecedor: Preencha de acordo com a máscara")
	@Column(name = "inscricaofornecedor", nullable = false, length = 18)
	public String getInscricaofornecedor() {
		return this.inscricaofornecedor;
	}

	public void setInscricaofornecedor(String inscricaofornecedor) {
		this.inscricaofornecedor = inscricaofornecedor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "responsavel")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

}
